### ISSUE TITLE
authenticate

### ISSUE THREAD

**Issue by FlaxLowbreeze** [Fitzy1293/reddit#1]
Hi what is the authenticate modul and how do i import it 
i have tried pip install authenticate

and what python do you use ?

**Comment by Fitzy1293** [comment]
The authenticate module is a module I made that contains authentification info to use the reddit api. Using the pip won't work. Sorry for the confusion!
This is what it looks like.

import praw
def authenticate():
    reddit = praw.Reddit(client_id='YOUR CLIENT ID',
                         client_secret='YOUR CLIENT SECRET',
                         user_agent='URL OF YOUR SCRIPT',
                         username='/u/YOU')
    return reddit

I do this so I don't I can push it to github without changing it everytime.  

I'm using python 3.7.

**Comment by Fitzy1293** [comment]
> Hi what is the authenticate modul and how do i import it
> i have tried pip install authenticate
> 
> and what python do you use ?

The authenticate module is a module I made that contains authentification info to use the reddit api. Using the pip won't work. Sorry for the confusion!
This is what it looks like.

import praw
def authenticate():
reddit = praw.Reddit(client_id='YOUR CLIENT ID',
client_secret='YOUR CLIENT SECRET',
user_agent='URL OF YOUR SCRIPT',
username='/u/YOU')
return reddit

I do this so I don't I can push it to github without changing it everytime.

I'm using python 3.7.
